name: CI Build

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    timeout-minutes: 10

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Build Tools
        run: |
          pip install --upgrade pip
          pip install build

      - name: Build Package
        run: python -m build example_fastapi_app-main/ --outdir dist/
      
      - name: Upload Package Artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-package-dist
          path: dist/
          retention-days: 1

  build-docker-image:
    needs: build
    timeout-minutes: 10

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Package Artifact
        uses: actions/download-artifact@v4
        with:
          name: python-package-dist
          path: dist

      - name: Build Docker Image
        run: |
          docker build -t example-fastapi-app:latest .
      
      - name: Verify Build
        run: docker images